### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by avrybrdly93** [avrybrdly93/Project1#4]
This is another place we can add features we want to add to our app

**Comment by kfillpot** [comment]
Wishlist ( so far ):

- Signup and login
- Save searches
- Rate shops, hotels, and events
- Giving user suggestions based on other user's with similar interests
- Provide time it will take the user to get to a chosen area based on location of activity and mode of tranportation (bus, taxi, uber, walking, etc.)
- Providing incentives for customer's to rate businesses
